### ISSUE TITLE
Use purposeful conda download API

### ISSUE THREAD

**Issue by dholth** [conda/conda-libmamba-solver#114]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

conda-libmamba-solver should not subclass SubdirData.

Could it possibly use the new repodata gateway class?

See also https://github.com/conda/conda/pull/12050 which allows a normal SubdirData fetch (cache file mamba wants written as a side effect) to be quick; although it also wouldn't be surprising if we eventually change the cache's disk format.

**Comment by dholth** [comment]
This rough draft API saves repodata.json to a file, to avoid double-writes vis. incremental repodata https://github.com/conda/conda/pull/12090/commits/2625090ef69462c92b576e305c4f6520eb16e872

**Comment by costrouc** [comment]
@jaimergp I'll take on this issue since this continues on the work that I was doing in #119.

**Comment by costrouc** [comment]
So wanted to dump my understanding of this as I work through it since this codebase is quite new to me. I am trying to understand https://github.com/costrouc/conda-libmamba-solver/blob/bug-issue-118/conda_libmamba_solver/index.py#L157-L188. In order for me to test these things out I needed to properly initialize conda logging.

```python
from conda.gateways.logging import initialize_std_loggers
initialize_std_loggers()
```

Next let's just take an arbitrary channel + subdir `noarch` in this case

```python
from conda.models.channel import Channel
channel = Channel.from_url('https://conda.anaconda.org/conda-forge/noarch')
```

Next we use the SubdirData class that is used here and for some reason replaced by @jaimergp's ``_DownloadOnlySubdirDat`a .

````python
  from conda.core.subdir_data import SubdirData
  subdir_data = SubdirData(channel)
  subdir_data.load()
  # does several things
  #  - function downloads repodata.json unless offline or file last modified is different
  #  - next processes self._process_raw_repodata_str(...)
  #    - load repodata.json file
  #    - read all of the packages in repodata.json self._process_raw_repodata
```

When I dive into reading https://github.com/conda/conda/blob/main/conda/core/subdir_data.py#L229 I see many calls but essentially this function is:
  - downloading the repodata.json in a cacheable location
  - not downloading if offline/has already been cached, orrepodata.json hasn't been modified since via s3 http headers
  - next read in json repodata.json file
  - finally do all the parsing of this file and store into `self._internal_state` 

All this is wasteful if we only want to download the `repodata.json` for that given channel + subdir. Hence the function that @jaimergp wrote.

**Comment by costrouc** [comment]
Okay now that I understand the history on this. I get that what we are trying to avoid is realizing the PackageRecords since this is expensive. I looks like https://github.com/conda/conda/pull/12050 if a newer conda version is used does pretty much this (though still reads the repodata.json file).

So if we still were to use SubdirData we would just want to use the existing one and no longer use `_DownloadSubdirData`.

@dholth if I am understanding what is being asked here is to replace https://github.com/costrouc/conda-libmamba-solver/blob/bug-issue-118/conda_libmamba_solver/index.py#L161-L188 with using the repodata gateway interface seen in https://github.com/conda/conda/blob/main/conda/gateways/repodata/__init__.py#L1 is that right?

**Comment by costrouc** [comment]
I would need to subclass `CondaRepoInterface` for now since it handles the download logic for the repodata.json. And I would then need to cache the file in the correct location (doesn't matter too much what that is but it would be nice if it matched conda's behaviour. Then would call the `libmamba.api` object with the correct inputs seen in https://github.com/costrouc/conda-libmamba-solver/blob/bug-issue-118/conda_libmamba_solver/index.py#L152-L154.

@jaimergp correct me if I'm on the wrong path but I'm getting from this that I need to:
  - use the conda gateway class `CondaRepoInterface`
  - take the string from that class and write to a repodata.json file somewhere (try to emulate conda's cache filename)
  - feed these inputs in the libmamba api.Repo class.

**Comment by dholth** [comment]
It would be reasonable to keep whatever libmamba-solver is doing, until the March conda release which will have much less PackageRecord overhead (measure the overhead).

If the overhead is still too much, we should submit a patch to conda adding a "download to cache only" flag to conda's SubdirData. SubdirData is going to grow logic to choose between alternative CondaRepoInterface.

**Comment by costrouc** [comment]
@jaimergp will open a PR if this is the right direction

````
import os

from conda.core.subdir_data import create_cache_dir, cache_fn_url
from conda.models.channel import Channel
from conda.base.constants import REPODATA_FN

def cached_repodata_filename(url: str, repodata_fn: str = REPODATA_FN):
    channel = Channel.from_url(url)
    return os.path.join(create_cache_dir(), cache_fn_url(channel.url(with_credentials=True) or ""))

from conda.gateways.repodata import CondaRepoInterface

state = {}
url = 'https://conda.anaconda.org/conda-forge/noarch'
repodata_filename = cached_repodata_filename(url, REPODATA_FN)
repodata = CondaRepoInterface(url, REPODATA_FN)
with open(repodata_filename, 'w') as f:
    f.write(repodata.repodata(state))

import libmambapy as api
pool = api.Pool()
repo = api.Repo(pool, url, repodata_filename, url)

```

**Comment by dholth** [comment]
Will need to go through SubdirData, not use any CondaRepoInterface directly. SubdirData will own complex logic to update the cache with locking. Writing directly to the cache will invalidate it.

**Comment by costrouc** [comment]
Thanks @dholth for the feedback. Not sure if I completely follow. So

> conda-libmamba-solver should not subclass SubdirData.

> Could it possibly use the new repodata gateway class?

Does this issue still hold? Currently it is in the `23.2.0 ` roadmap. Looks like you said this should be in the `23.3.0` release then. cc @jezdez

**Comment by jaimergp** [comment]
I think we are fine now here, after merging #59 with this block:

https://github.com/conda/conda-libmamba-solver/blob/27c7d61a27e7a16c3f3569fa69392e05dcb65381/conda_libmamba_solver/index.py#L204-L208
