### ISSUE TITLE
Adopt new subdir/repodata API from upstream conda (@dholth's work)

### ISSUE THREAD

**Issue by jezdez** [conda/conda-libmamba-solver#135]

**Comment by jaimergp** [comment]
Can I have more info on this new API, @dholth? I've seen there's a `RepodataInterface` but that one doesn't check for the cache, right?

Ideally, what I'd like to use is a class (or a method of a class) that:

- Validates channel name / URL / path
- Checks if cache exists and is up-to-date.
- Load it from the cache if the point above is true
- Download from the remote otherwise, and populate the cache / states
- It should _not_ attempt to parse the JSON

Do we have such a setup right now?

**Comment by dholth** [comment]
This API is changing. https://github.com/conda/conda/pull/12090/files#diff-ff8022ba5d08310acbbc6f95e1bc77a53f69e00ffe6daa51026af8880f89612dR362

It's also demonstrated in this new test function https://github.com/conda/conda/blob/features/repodata-jlap/tests/gateways/test_jlap.py#L304 where you can ask SubdirData for the RepoInterface; pass it the state containing cache headers (now a class instead of a bare dict), and sometimes you get a "RepodataOnDisk" exception instead of the parsed json. Yes `RepoInterface` checks/follows the caching rules. The caller is also responsible for writing the cache headers back to disk though.

What are we trying to accomplish?

Very soon we need to add API to deal with locking correctly, to do all the cache/update saved headers automatically, and to prefer either parsed or not-parsed json (sometimes the cache must parse repodata.json anyway and would otherwise write-to-disk-and-reread) so that the caller can avoid all extra json parsing.

**Comment by jaimergp** [comment]
Closing as part of #59
