### ISSUE TITLE
Upcoming changes in mamba context breaks conda-libmamba-solver

### ISSUE THREAD

**Issue by costrouc** [conda/conda-libmamba-solver#192]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The following commit to mamba https://github.com/mamba-org/mamba/pull/2432/ changes the way in which the context object is constructed. This means the next libmambapy version will break conda-libmamba-solver. Will be opening a PR on the fixes but the bigger question is how to preserve compatibility with older libmamba versions.

We are going to have to continue with repodata patches potentially due to this? Hope this issue/PR opens a larger discussion.

```python
ctx = libmambapy.context.Context()
ctx.json # Attribute Error
ctx.output_config.json # exists 
```

**Comment by jezdez** [comment]
Generally speaking we should have a close feedloop with the mamba maintainers about these changes and encourage no breaking/API changes in dot releases. Repodata patching is okay if there is no other way to keep the API from breaking, although I'd hope we could collaborate on feature changes ahead of time instead of running into the problem again and again.

@AntoinePrv Would you be interested in joining the conda-libmamba-solver team to improve the communication when you plan or conduct changes upstream? Right now it's just @wolfv and this might not be enough for a high bandwidth communicatino.

Also, is there anything the conda-libmamba-solver team can do to make it easier for us to stay aligned?

**Comment by AntoinePrv** [comment]
@jezdez I'd be happy to join, where can I find he details? If you have more concerns, also feel free to attend the bi-weekly  [mamba community meeting](https://github.com/mamba-org/mamba/#biweekly-dev-meeting).

We are working on a big refactoring, completely restructuring the internals of libmamba, but we are committed to not break the `libmambapy` on patch and minor releases (major release will come by the end of the year).

Regarding, https://github.com/mamba-org/mamba/pull/2432, I think @jaimergp and @Hind-M clarified changes yesterday.

**Comment by Hind-M** [comment]
The changes concerning the `Context` are not included in the releases. And we are also planning a PR to still have both APIs supported. The best way to be updated regarding the ongoing work on mamba is to attend the mamba meeting as suggested by Antoine indeed :)
