### ISSUE TITLE
warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE

### ISSUE THREAD

**Issue by SysuJayce** [conda/conda-libmamba-solver#348]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I tried to install some packages using `conda install -y -c conda-forge --override-channels dawg` and stuck in `solving environment` for hours.

Here is what I got: `Solving environment: / warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE`

BTW, I set the solver to libmamba before install packages via conda: `conda config --set solver libmamba`

### Conda Info

```shell
active environment : None
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 23.9.0
    conda-build version : not installed
         python version : 3.11.6.final.0
       virtual packages : __archspec=1=x86_64_v3
                          __glibc=2.35=0
                          __linux=3.10.107=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/23.9.0 requests/2.31.0 CPython/3.11.6 Linux/3.10.107-1-tlinux2_kvm_guest-0053 ubuntu/22.04.3 glibc/2.35 solver/libmamba conda-libmamba-solver/23.9.3 libmambapy/1.5.1
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /root/.condarc <==
solver: libmamba
```

### Conda list

```shell
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
archspec                  0.2.1              pyhd8ed1ab_1    conda-forge
blas                      2.116                       mkl    conda-forge
blas-devel                3.9.0            16_linux64_mkl    conda-forge
boltons                   23.0.0          py311h06a4308_0    defaults
brotli-python             1.0.9           py311h6a678d5_7    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.19.1               h5eee18b_0    defaults
ca-certificates           2023.08.22           h06a4308_0    defaults
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311h5eee18b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.9.0          py311h38be061_2    conda-forge
conda-content-trust       0.2.0           py311h06a4308_0    defaults
conda-libmamba-solver     23.9.3          py311h06a4308_0    defaults
conda-package-handling    2.2.0           py311h06a4308_0    defaults
conda-package-streaming   0.9.0           py311h06a4308_0    defaults
cryptography              41.0.3          py311hdda0065_0    defaults
cuda-cudart               11.8.89                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cudatoolkit               11.8.0              h4ba93d1_12    conda-forge
filelock                  3.13.1             pyhd8ed1ab_0    conda-forge
fmt                       9.1.0                hdb19cb5_0    defaults
gmp                       6.2.1                h58526e2_0    conda-forge
gmpy2                     2.1.2           py311h6a5fa03_1    conda-forge
icu                       73.1                 h6a678d5_0    defaults
idna                      3.4             py311h06a4308_0    defaults
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
krb5                      1.20.1               h143b758_1    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libarchive                3.6.2                h6ac8c49_2    defaults
libblas                   3.9.0            16_linux64_mkl    conda-forge
libcblas                  3.9.0            16_linux64_mkl    conda-forge
libcublas                 11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufile                 1.8.0.34                      0    nvidia
libcurand                 10.3.4.52                     0    nvidia
libcurl                   8.4.0                h251f7ec_0    defaults
libcusolver               11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libedit                   3.1.20221030         h5eee18b_0    defaults
libev                     4.33                 h7f8727e_1    defaults
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 13.2.0               h807b86a_2    conda-forge
libgfortran-ng            13.2.0               h69a702a_2    conda-forge
libgfortran5              13.2.0               ha4646dd_2    conda-forge
libgomp                   13.2.0               h807b86a_2    conda-forge
libhwloc                  2.9.1                hd6dc26d_0    conda-forge
liblapack                 3.9.0            16_linux64_mkl    conda-forge
liblapacke                3.9.0            16_linux64_mkl    conda-forge
libmamba                  1.5.1                haf1ee3a_0    defaults
libmambapy                1.5.1           py311h2dafd23_0    defaults
libnghttp2                1.57.0               h2d74bed_0    defaults
libnpp                    11.8.0.86                     0    nvidia
libnsl                    2.0.1                hd590300_0    conda-forge
libnvjpeg                 11.9.0.86                     0    nvidia
libsolv                   0.7.24               he621ea3_0    defaults
libsqlite                 3.43.2               h2797004_0    conda-forge
libssh2                   1.10.0               hdbd6064_2    defaults
libstdcxx-ng              13.2.0               h7e041cc_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxml2                   2.10.4               hf1b16e4_1    defaults
libzlib                   1.2.13               hd590300_5    conda-forge
llvm-openmp               15.0.7               h0cdce71_0    conda-forge
lz4-c                     1.9.4                h6a678d5_0    defaults
markupsafe                2.1.3           py311h459d7ec_1    conda-forge
mkl                       2022.1.0           h84fe81f_915    conda-forge
mkl-devel                 2022.1.0           ha770c72_916    conda-forge
mkl-include               2022.1.0           h84fe81f_915    conda-forge
mpc                       1.3.1                hfe3b2da_0    conda-forge
mpfr                      4.2.1                h9458935_0    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h6a678d5_0    defaults
networkx                  3.2.1              pyhd8ed1ab_0    conda-forge
openssl                   3.1.4                hd590300_0    conda-forge
packaging                 23.1            py311h06a4308_0    defaults
pcre2                     10.42                hebb0a14_0    defaults
pip                       23.2.1          py311h06a4308_0    defaults
pluggy                    1.0.0           py311h06a4308_1    defaults
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.6           py311h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.2.0          py311h06a4308_0    defaults
pysocks                   1.7.1           py311h06a4308_0    defaults
python                    3.11.6          hab00c5b_0_cpython    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytorch                   2.1.0           py3.11_cuda11.8_cudnn8.7.0_0    pytorch
pytorch-cuda              11.8                 h7e8668a_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pyyaml                    6.0.1           py311h459d7ec_1    conda-forge
readline                  8.2                  h5eee18b_0    defaults
reproc                    14.2.4               h295c915_1    defaults
reproc-cpp                14.2.4               h295c915_1    defaults
requests                  2.31.0          py311h06a4308_0    defaults
ruamel.yaml               0.17.21         py311h5eee18b_0    defaults
setuptools                68.0.0          py311h06a4308_0    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
sympy                     1.12            pypyh9d50eac_103    conda-forge
tbb                       2021.9.0             hf52228f_0    conda-forge
tk                        8.6.13               h2797004_0    conda-forge
torchtriton               2.1.0                     py311    pytorch
tqdm                      4.65.0          py311h92b7b1e_0    defaults
truststore                0.8.0           py311h06a4308_0    defaults
typing_extensions         4.8.0              pyha770c72_0    conda-forge
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.18         py311h06a4308_0    defaults
wheel                     0.41.2          py311h06a4308_0    defaults
xz                        5.4.2                h5eee18b_0    defaults
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.7.0                h295c915_1    defaults
zlib                      1.2.13               hd590300_5    conda-forge
zstandard                 0.19.0          py311h5eee18b_0    defaults
zstd                      1.5.5                hc292b87_0    defaults
```

**Comment by jaimergp** [comment]
Hi, thanks for the report! I'll need some more details:

* Were you installing `dawg` on the environment listed in the `conda list` section? 
* Can you provide the `history` file for that environment? It should be under `$CONDA_PREFIX/conda-meta/history` (activate the env first).
* Additionally, can you run the same command with extra verbosity and copy it to a file? Something like this should work (attach the file, zipped if needed).

```
$ conda install conda install -y -c conda-forge --override-channels -vvv dawg 2>&1 | tee log.txt
```


Assuming you are running this on the listed env, that environment is combining a lot of heavy channels. Without strict priority, that can take a while. So I suggest doing one of the following:

```
$ conda install conda install -y -c conda-forge --override-channels dawg --strict-channel-priority
```

```
$ CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED=1 conda install conda install -y -c conda-forge --override-channels dawg --strict-channel-priority
```

```
$ CONDA_LIBMAMBA_SOLVER_MAX_ATTEMPTS=5 CONDA_LIBMAMBA_SOLVER_NO_CHANNELS_FROM_INSTALLED=1 conda install conda install -y -c conda-forge --override-channels dawg --strict-channel-priority
```


Hopefully that will reduce the time needed to error out, but it might also give slightly different solutions.

**Comment by jaimergp** [comment]
Hey @SysuJayce, there's been a new release (23.11.0) which might help diagnose your issue better. Let me know if you got a chance to try. Thanks!

**Comment by SysuJayce** [comment]
> Hey @SysuJayce, there's been a new release (23.11.0) which might help diagnose your issue better. Let me know if you got a chance to try. Thanks!

Hello @jaimergp , I apologize for the inconvenience. I have discovered that this error is caused by the `dawg` library, which is not compatible with Python 3.11.

**Comment by jaimergp** [comment]
The final error should have provided some kind of information in that direction. I've never seen this solver get stuck for hours though, so that was a bit concerning.

For now I'm going to close, but feel free to reopen with the information I requested above if you need to! Thanks!

**Comment by rootsmusic** [comment]
@jaimergp Can this warning cause conda to falsely return "All requested packages already installed", when the installed version is not the latest version available in conda-forge?  Thanks.

**Comment by jaimergp** [comment]
Which command are you using? update or install?

**Comment by luillyfe** [comment]
This baby made the trick:

`conda config --set solver classic `

I was using the following command:

`conda install pytorch-nightly::pytorch torchvision torchaudio -c pytorch-nightly`

I couldn't get that to work until I use the classic dependency solver.

**Comment by manna1lix** [comment]
hello i have this issue when i try installing tensorflow-gpu  and some of them are green and some of them are red ... 


Solving environment: - warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides bleach 1.5.0 needed by tensorboard-1.8.0-py310h6c2663c_0

Could not solve for environment specs
The following packages are incompatible
├─ pin-1 is installable and it requires
│  └─ python 3.9.* , which can be installed;
├─ spyder is installable with the potential options
│  ├─ spyder [5.3.3|5.4.1|5.4.2|5.4.3|5.5.1] would require
│  │  └─ pyqtwebengine [<5.16 |>=5.10,<5.16 |>=5.15,<5.16 ] with the potential options
│  │     ├─ pyqtwebengine 5.15.10 would require
│  │     │  └─ qt-main 5.15.*  with the potential options
│  │     │     ├─ qt-main 5.15.2 would require
│  │     │     │  └─ icu >=73.1,<74.0a0 , which can be installed;
│  │     │     └─ qt-main 5.15.2 would require
│  │     │        └─ icu >=58.2,<59.0a0 , which can be installed;
│  │     ├─ pyqtwebengine [5.15.10|5.15.7] would require
│  │     │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
│  │     ├─ pyqtwebengine [5.15.10|5.15.7] would require
│  │     │  └─ python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported;
│  │     ├─ pyqtwebengine 5.15.10 would require
│  │     │  └─ python >=3.12,<3.13.0a0 , which conflicts with any installable versions previously reported;
│  │     ├─ pyqtwebengine [5.15.10|5.15.7] would require
│  │     │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
│  │     ├─ pyqtwebengine 5.15.7 would require
│  │     │  └─ python >=3.7,<3.8.0a0 , which conflicts with any installable versions previously reported;
│  │     └─ pyqtwebengine 5.15.7 would require
│  │        └─ qtwebkit 5.* , which requires
│  │           └─ icu >=58.2,<59.0a0 , which can be installed;
│  ├─ spyder [3.2.3|3.2.4|...|4.0.1] would require
│  │  └─ python >=2.7,<2.8.0a0 , which conflicts with any installable versions previously reported;
│  ├─ spyder [3.2.3|3.2.4|...|3.3.1] would require
│  │  └─ python >=3.5,<3.6.0a0 , which conflicts with any installable versions previously reported;
│  ├─ spyder [3.2.3|3.2.4|...|5.0.5] would require
│  │  └─ python >=3.6,<3.7.0a0 , which conflicts with any installable versions previously reported;
│  ├─ spyder [3.3.0|3.3.1|...|5.3.3] would require
│  │  └─ python >=3.7,<3.8.0a0 , which conflicts with any installable versions previously reported;
│  ├─ spyder [4.0.1|4.1.0|...|5.5.1] would require
│  │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
│  ├─ spyder [4.2.0|4.2.1|...|5.1.5] would require
│  │  └─ pyqt >=5.6,<5.13  with the potential options
│  │     ├─ pyqt [5.15.10|5.15.7|5.9.2] would require
│  │     │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
│  │     ├─ pyqt [5.15.10|5.15.7|5.9.2] would require
│  │     │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
│  │     ├─ pyqt [5.15.7|5.6.0|5.9.2] would require
│  │     │  └─ python >=3.7,<3.8.0a0 , which conflicts with any installable versions previously reported;
│  │     ├─ pyqt [5.15.7|5.9.2] would require
│  │     │  ├─ qt >=5.9.7,<5.10.0a0 , which requires
│  │     │  │  └─ icu >=58.2,<59.0a0 , which can be installed;
│  │     │  └─ qtwebkit 5.* , which can be installed (as previously explained);
│  │     ├─ pyqt 5.6.0 would require
│  │     │  └─ python >=2.7,<2.8.0a0 , which conflicts with any installable versions previously reported;
│  │     ├─ pyqt [5.6.0|5.9.2] would require
│  │     │  └─ python >=3.5,<3.6.0a0 , which conflicts with any installable versions previously reported;
│  │     └─ pyqt [5.6.0|5.9.2] would require
│  │        └─ python >=3.6,<3.7.0a0 , which conflicts with any installable versions previously reported;
│  ├─ spyder [5.1.5|5.2.2|...|5.5.1] would require
│  │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
│  ├─ spyder 5.2.2 would require
│  │  └─ pyqt >=5.6  with the potential options
│  │     ├─ pyqt 5.15.10 would require
│  │     │  └─ qt-main 5.15.* , which can be installed (as previously explained);
│  │     ├─ pyqt [5.15.10|5.15.7|5.9.2], which cannot be installed (as previously explained);
│  │     ├─ pyqt [5.15.10|5.15.7] would require
│  │     │  └─ python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported;
│  │     ├─ pyqt 5.15.10 would require
│  │     │  └─ python >=3.12,<3.13.0a0 , which conflicts with any installable versions previously reported;
│  │     ├─ pyqt [5.15.10|5.15.7|5.9.2], which cannot be installed (as previously explained);
│  │     ├─ pyqt [5.15.7|5.6.0|5.9.2], which cannot be installed (as previously explained);
│  │     ├─ pyqt [5.15.7|5.9.2], which can be installed (as previously explained);
│  │     ├─ pyqt 5.6.0, which cannot be installed (as previously explained);
│  │     ├─ pyqt [5.6.0|5.9.2], which cannot be installed (as previously explained);
│  │     └─ pyqt [5.6.0|5.9.2], which cannot be installed (as previously explained);
│  ├─ spyder [5.4.1|5.4.2|5.4.3|5.5.1] would require
│  │  └─ python >=3.11,<3.12.0a0 , which conflicts with any installable versions previously reported;
│  └─ spyder 5.5.1 would require
│     └─ python >=3.12,<3.13.0a0 , which conflicts with any installable versions previously reported;
└─ tensorflow-gpu is not installable because there are no viable options
   ├─ tensorflow-gpu [1.10.0|1.9.0] would require
   │  └─ tensorflow [1.10.0 |1.9.0 ] but there are no viable options
   │     ├─ tensorflow [1.10.0|1.9.0] would require
   │     │  └─ python 3.5.* , which conflicts with any installable versions previously reported;
   │     └─ tensorflow [1.10.0|1.11.0|...|2.1.0] would require
   │        └─ python 3.6.* , which conflicts with any installable versions previously reported;
   ├─ tensorflow-gpu [1.11.0|1.12.0] would require
   │  └─ tensorflow [1.11.0 |1.12.0 ], which cannot be installed (as previously explained);
   ├─ tensorflow-gpu [1.13.1|1.14.0|1.15.0|2.0.0|2.1.0] would require
   │  └─ tensorflow [1.13.1 |1.14.0 |1.15.0.* |2.0.0 |2.1.0 ] but there are no viable options
   │     ├─ tensorflow [1.13.1|1.14.0|...|2.6.0] would require
   │     │  └─ python 3.7.* , which conflicts with any installable versions previously reported;
   │     └─ tensorflow [1.10.0|1.11.0|...|2.1.0], which cannot be installed (as previously explained);
   ├─ tensorflow-gpu 1.8.0 would require
   │  └─ tensorboard >=1.8.0,<1.9.0 , which requires
   │     └─ bleach 1.5.0 , which does not exist (perhaps a missing channel);
   ├─ tensorflow-gpu 2.3.0 would require
   │  └─ tensorflow 2.3.0  but there are no viable options
   │     ├─ tensorflow [1.13.1|1.14.0|...|2.6.0], which cannot be installed (as previously explained);
   │     └─ tensorflow [2.3.0|2.5.0|2.6.0] would require
   │        └─ python 3.8.* , which conflicts with any installable versions previously reported;
   └─ tensorflow-gpu [2.5.0|2.6.0] would require
      └─ tensorflow [2.5.0 |2.6.0 ] but there are no viable options
         ├─ tensorflow [1.13.1|1.14.0|...|2.6.0], which cannot be installed (as previously explained);
         ├─ tensorflow [2.3.0|2.5.0|2.6.0], which cannot be installed (as previously explained);
         └─ tensorflow [2.5.0|2.6.0] would require
            └─ tensorflow-base [2.5.0 eigen_py39h03e61e6_0|2.5.0 gpu_py39hb3da07e_0|...|2.6.0 mkl_py39h9201259_0], which requires
               └─ icu >=68.1,<69.0a0 , which conflicts with any installable versions previously reported.
